### ISSUE TITLE
Running the example makefile gives Linker error

### ISSUE THREAD

**Issue by wiesener** [nordic-auko/nRF5-ble-timesync-demo#12]
Hi,
when I run the example in the examples/ble_peripheral/ble_app_uart/pca10056/s140/armgcc folder I am getting:

undefined reference to `nrfx_ppi_channel_alloc'

I guess this has to be added to the nrfx /src folder.

Kind regards,

**Comment by wiesener** [comment]
Okay only the sdk_config PPI_ENABLED was missing.

**Comment by nordic-auko** [comment]
Thanks! I'll add the missing config
