### ISSUE TITLE
uart_peripheral Fatal error when connecting

### ISSUE THREAD

**Issue by wiesener** [nordic-auko/nRF5-ble-timesync-demo#13]
Hi,

when I try to connect with the board configured as peripheral I cannot connect to the board and the JLINK console tells me a fatal error.

**Comment by wiesener** [comment]
NRF Connect app was used and the App is telling permanentely that the device is connecting.

**Comment by nordic-auko** [comment]
Hello, can you add the DEBUG define to the Makefile? This should generate a JLink/RTT printout saying which line in which file that produced the fatal error:

CFLAGS += -DDEBUG

**Comment by wiesener** [comment]
Okay my fault. There was an old bond left over. When I erased it started working.
