### ISSUE TITLE
Build error: undefined reference to `nrfx_ppi_channel_alloc'

### ISSUE THREAD

**Issue by Nyovelt** [nordic-auko/nRF5-ble-timesync-demo#20]
![image](https://user-images.githubusercontent.com/18253926/149739562-980fa697-e118-4ec5-a0e3-a7e176c0a5f6.png)

I have read #12 and enabled `NRFX_PPI_ENABLED` as shown in the screen, but the IDE still consider it as error.

**Comment by David140** [comment]
Hi Nyovelt,
I needed to make these changes to build the project:
    1. SDK_CONFIG: #define PPI_ENABLED 1 (it was 0)
    2. INSERTING: nrfx_ppi.c file inside the project
I think at the moment the branch is still bugged.

**Comment by quannguyen123456** [comment]
hi Mr David140
I did all 1 and 2, but still error
Do you have some ideas?
thank you very much.

**Comment by David140** [comment]
Hi,
> I did all 1 and 2, but still error

No, sorry, I don't know, I just did these steps and the code compiled.
But anyway the new branch is still bugged, I'm waiting the support of @nordic-auko.
Thanks

**Comment by Nyovelt** [comment]
I have switch to branch `sdk16` and worked well.
