### ISSUE TITLE
Porting timesync-demo to S140 and nRF52840-PCA10056

### ISSUE THREAD

**Issue by nickes** [nordic-auko/nRF5-ble-timesync-demo#4]
I tried to compile this example for my nrf52840-DK but I'm running into errors. I switched the examples/ble_central/ble_app_uart_c/main.c from the original SDK 14.2.0 with the ble_central/ble_app_uart_c/main.c. I also copied the time_sync files into the example folder.
Is it even possible to port this example "easily" to the nrf52840-DK?
I'm looking forward to your answers.

**Comment by nordic-auko** [comment]
Hi @nickes , sorry for the slow response on this one. I added an SDK 16 folder now with the same BLE Central and Peripheral examples as in the SDK 14 folder. I tested on nRF52832 and nRF52840 DKs without any issues using GCC.

**Comment by nickes** [comment]
thanks
